### PR TITLE
chore(npm): Upgraded to lastest vorpal, fixed broken tests

### LINKED ISSUE #61: Update to latest vorpal
I may be missing something, but it seems that the version of vorpal that vantage depends on is way out of date (389 commits?! https://github.com/dthree/vorpal/compare/31e079c04f5...c987b51). 

Is this really the case? And if so can the upgrade be made as there is a lot of missing functionality (autocomplete, validation etc)

Loving both projects but need to use vantage to be able to drop into runtime shell.

### PR DESCRIPTION
**Pull request by zakhenry**
Closes #61

### CODE REVIEW

**Comment by zakhenry** [comment]
appveyor is reporting the following:
```
Build started
git clone -q https://github.com/dthree/vantage.git C:\projects\vantage
git fetch -q origin +refs/pull/62/merge:
git checkout -qf FETCH_HEAD
Specify a project or solution file. The directory does not contain a project or solution file.
```
Is there a fix for this? All tests are passing on travis

**Comment by dthree** [comment]
Hey, thanks! Looks good.

Don't worry about AppVeyor, never got it working.

**Comment by zakhenry** [comment]
Ah I see, thanks 👍

**Comment by dthree** [comment]
Would you mind playing around a little bit with this before I publish to NPM? This is a large update, and I want to make sure there's nothing that escaped tests.

**Comment by zakhenry** [comment]
Yea of course, I have published to a scope package at https://www.npmjs.com/package/@xiphiaz/vantage so I'm testing away now. So far so good.

**Comment by dthree** [comment]
Yeah, noticed that. Nice. :+1:

**Comment by zakhenry** [comment]
Only issue noted so far is a trivial one as I was extending the session.log functionality (which is using undocumented apis anyway). I changed

```js
const originalLog = vantage.session.log;
vantage.session.log = function(...args){


  let prev = this._hist[this._hist.length - 1].split(' ').shift();
  const task = chalk.white('['+chalk.cyan(prev)+']');
  args.unshift(task);
  originalLog.apply(this, args);
};
```
to
```js
const originalLog = vantage.ui.log;
vantage.ui.log    = function (...args) {

  const cmd = this.parent._command;

  if (cmd) {
    const task = chalk.white('[' + chalk.cyan(cmd.command.split(' ').shift()) + ']');
    args.unshift(task);
  }

  originalLog.apply(this, args);
};
```

It actually works better anyway as the previous one had issues with the log prefixing when not in session context.

**Pull request merged**
